//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRSI.SOSFileUploaderNet4.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp")]
        public string SOSFileUploader_LogPath {
            get {
                return ((string)(this["SOSFileUploader_LogPath"]));
            }
            set {
                this["SOSFileUploader_LogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:50000")]
        public string SOSApi_ApiUrl {
            get {
                return ((string)(this["SOSApi_ApiUrl"]));
            }
            set {
                this["SOSApi_ApiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClientId")]
        public string SOSApi_ClientId {
            get {
                return ((string)(this["SOSApi_ClientId"]));
            }
            set {
                this["SOSApi_ClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClientSecret")]
        public string SOSApi_ClientSecret {
            get {
                return ((string)(this["SOSApi_ClientSecret"]));
            }
            set {
                this["SOSApi_ClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51000/connect/token")]
        public string IdentityServer_TokenEndpointUrl {
            get {
                return ((string)(this["IdentityServer_TokenEndpointUrl"]));
            }
            set {
                this["IdentityServer_TokenEndpointUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SOSFileUploader_StoreId {
            get {
                return ((string)(this["SOSFileUploader_StoreId"]));
            }
            set {
                this["SOSFileUploader_StoreId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\QSR")]
        public string SOSFileUploader_QsrSOSPath {
            get {
                return ((string)(this["SOSFileUploader_QsrSOSPath"]));
            }
            set {
                this["SOSFileUploader_QsrSOSPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\history.json")]
        public string SOSFileUploader_HistoryPath {
            get {
                return ((string)(this["SOSFileUploader_HistoryPath"]));
            }
            set {
                this["SOSFileUploader_HistoryPath"] = value;
            }
        }
    }
}
